@extends('layout.default')

@section('content')
    @include('partials.header')

    <!-- HERO WITH VIDEO BACKGROUND -->
    <section class="hero position-relative overflow-hidden d-flex align-items-center">
        <video autoplay muted loop playsinline class="position-absolute w-100 h-100" style="object-fit: cover; z-index: 0;">

            <source src="{{ asset('video/astrology-bgr.mp4') }}" type="video/mp4">
        </video>
        <div class="position-absolute w-100 h-100" style="background: rgba(11, 15, 26, 0.75); z-index: 1;"></div>

        <div class="container text-center position-relative" style="z-index: 2;">
            <span class="badge badge-ai mb-3">{{ __('AI-Powered Astrology') }}</span>
            <h1 class="display-4 mt-3">
                {{ __('Your Personalized Horoscope,') }}<br>
                {{ __('Generated by Artificial Intelligence') }}
            </h1>
            <p class="lead text-muted-custom mt-4">
                {{ __('Daily insights for love, career and life – tailored uniquely to you.') }}
            </p>
            <div class="mt-5">
                <a href="#pricing" class="btn btn-accent btn-lg me-3">{{ __('View Plans') }}</a>
                <a href="#how" class="btn btn-outline-light btn-lg">{{ __('How It Works') }}</a>
            </div>
        </div>
    </section>

    <!-- SERVICES -->
    <section class="py-5">
        <div class="container">
            <div class="row mb-5 text-center">
                <h2>{{ __('What You Receive') }}</h2>
                <p class="text-muted-custom">{{ __('AI-driven insights based on astrology and data analysis') }}</p>
            </div>
            <div class="row g-4">
                <div class="col-md-4">
                    <div class="card p-4 h-100">
                        <h4>{{ __('Daily Horoscope') }}</h4>
                        <p class="text-muted-custom">{{ __('Short, precise daily predictions aligned with your birth chart.') }}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-4 h-100">
                        <h4>{{ __('Love & Relationships') }}</h4>
                        <p class="text-muted-custom">{{ __('Compatibility insights, emotional cycles and timing.') }}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-4 h-100">
                        <h4>{{ __('Career & Finance') }}</h4>
                        <p class="text-muted-custom">{{ __('Decision timing, opportunities and long-term forecasts.') }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- HOW IT WORKS -->
    <section id="how" class="py-5 bg-black">
        <div class="container">
            <div class="row text-center mb-5">
                <h2>{{ __('How It Works') }}</h2>
            </div>
            <div class="row g-4">
                <div class="col-md-4 text-center">
                    <h5>{{ __('1. Enter Birth Details') }}</h5>
                    <p class="text-muted-custom">{{ __('Date, time and place of birth.') }}</p>
                </div>
                <div class="col-md-4 text-center">
                    <h5>{{ __('2. AI Analysis') }}</h5>
                    <p class="text-muted-custom">{{ __('Advanced algorithms process astrological patterns.') }}</p>
                </div>
                <div class="col-md-4 text-center">
                    <h5>{{ __('3. Instant Results') }}</h5>
                    <p class="text-muted-custom">{{ __('Receive accurate, personalized insights.') }}</p>
                </div>
            </div>
        </div>
    </section>

    <!-- PRICING -->
    <section id="pricing" class="py-5">
        <div class="container">
            <div class="row text-center mb-5">
                <h2>{{ __('Subscription Plans') }}</h2>
                <p class="text-muted-custom">{{ __('Choose the depth of insight that suits you') }}</p>
            </div>
            <div class="row g-4">
                <div class="col-md-4">
                    <div class="card p-4 text-center h-100">
                        <h4>{{ __('Basic') }}</h4>
                        <div class="price">$9</div>
                        <p class="text-muted-custom">{{ __('Daily horoscope access') }}</p>
                        <button class="btn btn-outline-light mt-3">{{ __('Get Started') }}</button>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-4 text-center h-100 border-warning">
                        <h4>{{ __('Premium') }}</h4>
                        <div class="price">$19</div>
                        <p class="text-muted-custom">{{ __('Daily, love and career insights') }}</p>
                        <button class="btn btn-accent mt-3">{{ __('Most Popular') }}</button>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-4 text-center h-100">
                        <h4>{{ __('VIP') }}</h4>
                        <div class="price">$39</div>
                        <p class="text-muted-custom">{{ __('Full personalized reports') }}</p>
                        <button class="btn btn-outline-light mt-3">{{ __('Subscribe') }}</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- AI CREDIBILITY & DISCLAIMER -->
    <section class="py-5 bg-black">
        <div class="container">
            <div class="row text-center mb-4">
                <h2>{{ __('AI Credibility & Transparency') }}</h2>
                <p class="text-muted-custom mt-2">{{ __('How our technology works and what it represents') }}</p>
            </div>
            <div class="row g-4">
                <div class="col-md-6">
                    <div class="card p-4 h-100">
                        <h5>{{ __('Powered by Artificial Intelligence') }}</h5>
                        <p class="text-muted-custom mt-3">
                            {{ __('Our horoscopes are generated using advanced artificial intelligence models trained on astrological knowledge, symbolic patterns, and statistical correlations.') }}
                        </p>
                        <p class="text-muted-custom">
                            {{ __('The system processes birth data and planetary configurations to deliver structured and consistent interpretations.') }}
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card p-4 h-100 border-warning">
                        <h5>{{ __('Important Disclaimer') }}</h5>
                        <p class="text-muted-custom mt-3">
                            {{ __('AI-generated horoscopes are provided for informational and entertainment purposes only and do not constitute medical, legal, financial, or psychological advice.') }}
                        </p>
                        <p class="text-muted-custom">
                            {{ __('Users are responsible for their own decisions and interpretations of the information provided.') }}
                        </p>
                        <p class="text-muted-custom">
                            {{ __('Astrology and AI-based interpretations are subjective and should be used as guidance, not absolute predictions.') }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    @push('scripts')
        <script>
            console.log('Скрипт от home.blade.php');
        </script>
    @endpush
@endsection